spring.datasource.url="jdbc:mysql://localhost:3306/College?useSSL=false&serverTimeZone=UTC&allowPublicKeyRetrieval=true"
spring.datasource.user=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto = none
spring.jpa.show-sgl=true
spring.hpa.properties.hibernate.format_sgl = true;
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8080

spring.main.web-application-type=servlet
spring.main.lazy-initialization=true